### ISSUE TITLE
Publish College Cloud Information on vlabs.ac.in page

### ISSUE THREAD

**Issue by vleadadmin** [openedx-vlead/college-cloud#8]
A page for  College Cloud information on vlabs.ac.in page

**Comment by sivashankerN** [comment]
By mistake, I only created above issue using Admin credentials

**Comment by sivashankerN** [comment]
* What is College Cloud edition of Virtual-Labs?
  College Cloud (CC) is a Portable-Edition for the Virtual-Labs.
  Institutes/Colleges can use this CC for the Virtual-Labs without any Internet connection. That means, Labs that are there in the online, all that labs are available in CC expect Videos.

* How can Institutes/Colleges requests for college cloud edition?  
  Institues/Colleged have to contact to Virtual-Labs manager over a mail. Mail ID : engg@vlabs.ac.in

* What are the requirements for a college to use the college cloud edition?
  Requirements for a College
  - Recommended System Configuration
    Processor : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   ( Model : intel-db75en)    
    RAM : 16 GB
    SMPS : 600 W
    CPUs: 8
    MotherBoard wattage: 77 W
  - 500 GB SATA
  - Wi-Fi Router
    Please choose any better Wi-Fi as we need to serve our College Cloud for 100-200 users
  - A Computer LAB room with at least 30-100 Systems/Desktops
  - A Network Input ( Swich, from where all labs will get DHCP IP) to LAB machines/Desktops. So that, College Cloud can be accessed over the LAN network. This will give us better results
  - A Systems Engineer has to have basic knowledge on CentOS,Networking
* How to deploy College Cloud edition? 
  - User manual for College Cloud deployment is at https://github.com/openedx-vlead/college-cloud-workshops/blob/master/src/user-manual-for-portablemedia.org
* What are the limitations?
  Server Grade machine ( IBM Xenon processor): No limitaions
  With the above Recommended System Configuration over the LAN using Wi-Fi router: 
  10-20 labs at a time for 100-200 users.
  With the above Recommended System Configuration only with Wi-Fi: 
  3-5 labs at time for 20-30 users.
  
* Contact us for any Help
  engg@vlabs.ac.in
* IRC-Channel 
   #VLEAD

**Comment by sivashankerN** [comment]
The above information has to be updated on http://vlabs.ac.in page

**Comment by sivashankerN** [comment]
The above information captured at https://github.com/openedx-vlead/college-cloud/blob/master/src/Info-on-vlabs-web-page.org

**Comment by sivashankerN** [comment]
Information has been updated at http://vlabs.ac.in:5959/college-cloud-edition
